services:
  app_backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: app_backend
    container_name: app_backend
    env_file:
      - .env.example
    environment:
      DB_HOST: app_database
      DB_PORT: 5432
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - app_database

  app_database:
    build: postgres
    container_name: app_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_MULTIPLE_DATABASES: ${DB_DATABASE:-app_db}
      TZ: "UTC"
      PGTZ: "UTC"
    ports:
      - "${DB_PORT:-5432}:5432"

volumes:
  postgres_data:
